aliases:
    fleeks: cd ~/.local/share/fleek
allow_broken: false
bling: high
blocklist: []
byo_git: true
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
    - go
    - just
    - yq
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: bash
systems:
    - arch: x86_64
      home: ""
      hostname: fleekdev
      os: linux
      username: bjk
track: nixos-unstable
unfree: true
users:
    - email: bketelsen@gmail.com
      name: Brian Ketelsen
      ssh_private_key_file: ~/.ssh/id_rsa
      ssh_public_key_file: ~/.ssh/id_rsa.pub
      username: bjk
